#!/usr/bin/env sh
set -eu

cd "$(dirname "$0")"
cache_dir="$PWD/.cache"

exec env XDG_CACHE_HOME="$cache_dir" sbcl --noinform --no-userinit --non-interactive \
  --eval '(require :asdf)' \
  --eval '(asdf:initialize-output-translations (quote (:output-translations :enable-user-cache :ignore-inherited-configuration)))' \
  --eval '(load (merge-pathnames ".qlot/setup.lisp" (truename ".")))' \
  --eval '(setf uiop/lisp-build:*compile-file-warnings-behaviour* :warn uiop/lisp-build:*compile-file-failure-behaviour* :warn)' \
  --eval '(asdf:load-asd (merge-pathnames "slt.asd" (truename ".")))' \
  --eval '(asdf:load-system :slt)' \
  --eval '(slt:launch-terminal)'
